services:
  - type: web
    name: ebac-social-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    autoDeployTrigger: commit
    healthCheckPath: /health/
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        value: ebac-social-api.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://ebac-social.onrender.com
  - type: web
    name: ebac-social
    runtime: static
    rootDir: frontend
    autoDeployTrigger: commit
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://ebac-social-api.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
